name: api_service_helper
description: ApiServices in Flutter uses Dio for HTTP requests, supporting GET, POST, PUT, and DELETE methods with data, authentication, and progress tracking.
version: 1.0.0
homepage: https://github.com/Pradipjadav05/api_service_helper.git

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

